version: "3" #docker version
services:
  db:
    image: mysql:8.0
    container_name: DB
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=mixue
      - MYSQL_USER=viet
      - MYSQL_ROOT_PASSWORD=123asd
      - MYSQL_PASSWORD=123asd321
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - "./DB:/docker-entrypoint-initdb.d" # this is database created on when we run
  web:
    container_name: WEB
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - "./src/WEB:/var/www/html"
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: PHPMYADMIN_Web
    ports:
      - 81:80
    environment:
      - PMA_HOST=db
